apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: {{ .Values.hpa.metric }}
          selector:
            matchLabels:
              service: {{ .Release.Name }}
              namespace: {{ .Release.Namespace }}
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.averageValue }}